// <auto-generated />
using System;
using ContentWriter.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContentWriter.Infrastructure.Migrations
{
    [DbContext(typeof(ContentWriterDbContext))]
    [Migration("20260717182053_AddBatchPipeline")]
    partial class AddBatchPipeline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content_writer_v2")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContentWriter.Domain.Entities.BatchJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletedItems")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedItems")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("BatchJobs", "content_writer_v2");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.BatchJobItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchJobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorText")
                        .HasColumnType("text");

                    b.Property<int>("PreferredProvider")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetKeyword")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("BatchJobId");

                    b.HasIndex("ProjectId");

                    b.ToTable("BatchJobItems", "content_writer_v2");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.BatchJobItemStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("BatchJobItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorText")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StepName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchJobItemId", "StepName")
                        .IsUnique();

                    b.ToTable("BatchJobItemSteps", "content_writer_v2");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients", "content_writer_v2");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.CrawledSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CrawledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedFocus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetectedTone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Headings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JsonLdBlocks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PagesCrawled")
                        .HasColumnType("integer");

                    b.Property<string>("Paragraphs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("CrawledSites", "content_writer_v2");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.GeneratedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdvertisingSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlogSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentListExcerpt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayTitle")
                        .HasColumnType("text");

                    b.Property<string>("GeneratedByModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GeneratedByProvider")
                        .HasColumnType("integer");

                    b.Property<string>("HeroSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JsonLdSchema")
                        .HasColumnType("text");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MainSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedArticleUrl")
                        .HasColumnType("text");

                    b.Property<string>("SectionOutline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SourceAppName")
                        .HasColumnType("text");

                    b.Property<int?>("SourceAppOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ToolPageExcerpt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("GeneratedContents", "content_writer_v2");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.KeywordSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ExtractedHeadings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedParagraphs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedQuestions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedTitle")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("KeywordSources", "content_writer_v2");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PreferredProvider")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetKeyword")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Projects", "content_writer_v2");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.PublishTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyEnvVar")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("CategoryStrategy")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DefaultAuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("GeekBackendApiBaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("PublishTargets", "content_writer_v2");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.BatchJob", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.BatchJobItem", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.BatchJob", "BatchJob")
                        .WithMany("Items")
                        .HasForeignKey("BatchJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentWriter.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BatchJob");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.BatchJobItemStep", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.BatchJobItem", "BatchJobItem")
                        .WithMany("Steps")
                        .HasForeignKey("BatchJobItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchJobItem");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.CrawledSite", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.Project", "Project")
                        .WithOne("CrawledSite")
                        .HasForeignKey("ContentWriter.Domain.Entities.CrawledSite", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.GeneratedContent", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.Project", "Project")
                        .WithMany("GeneratedContents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.KeywordSource", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.Project", "Project")
                        .WithMany("KeywordSources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.Project", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.PublishTarget", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.Client", "Client")
                        .WithOne("PublishTarget")
                        .HasForeignKey("ContentWriter.Domain.Entities.PublishTarget", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.BatchJob", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.BatchJobItem", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.Client", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("PublishTarget");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.Project", b =>
                {
                    b.Navigation("CrawledSite");

                    b.Navigation("GeneratedContents");

                    b.Navigation("KeywordSources");
                });
#pragma warning restore 612, 618
        }
    }
}
